### PR TITLE
Use full date for the year

### PR DESCRIPTION
**Pull request by davisonio**
This simply changes the present year to be in the full year format.

I think this is a better way because if you set the starting year to `1999` then the license will show `1999-16` which isn't correct!

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@davisonio Thanks! But maybe, can we make this smarter: if the prefix is the same, then show it like `YYYY-YY` otherwise `YYYY-YYYY`? :thought_balloon:

**Comment by IonicaBizau** [comment]
@davisonio :bell:

**Comment by IonicaBizau** [comment]
@davisonio This is now possible using [`year-range`](https://github.com/IonicaBizau/year-range). If you can integrate it here, that's fine, otherwise I will take care of it. :smile:

**Comment by davisonio** [comment]
> @davisonio This is now possible using year-range. If you can integrate it here, that's fine, otherwise I will take care of it.

Awesome, feel free to take care of it :)

**Comment by IonicaBizau** [comment]
@davisonio Well, I will continue your work and merge this.

:gift: Bonus, you'll get a shiny green square on your contributions calendar. :grin:

**Comment by IonicaBizau** [comment]
I'm on it. :crystal_ball:

**Comment by davisonio** [comment]
Thank you 😃

**Comment by IonicaBizau** [comment]
@davisonio This is now landed on production (/cc #9). :rocket: Thanks again for heads-up! 

:ship: Also, `npm publish`ed **`1.1.2`** :tada:

**Comment by IonicaBizau** [comment]
@davisonio And [there you go](https://github.com/davisonio?tab=contributions&from=2016-01-02)! :smile: 

image

**Pull request merged**
